### ISSUE TITLE
windows

### ISSUE THREAD

**Issue by mixmix** [ahdinosaur/require-style#1]
doesn't quite work with font-awesome in windows yet. 

error looks like erorr, can't find : 

```
file:///C:/Usersmixmixprojectspatchbaynode_modules%0Font-awesome%0Fonts/fontawesome-webfont.woff2?v=4.7.0
```

**Comment by mixmix** [comment]
Here we go... here's the problem css it's creating : 

```css
@font-face {
  font-family: 'FontAwesome';
  src: url(C:\Users\mixmix\projects\ticktack-wp1\node_modules\font-awesome\fonts/fontawesome-webfont.eot?v=4.7.0);
  src: url(C:\Users\mixmix\projects\ticktack-wp1\node_modules\font-awesome\fonts/fontawesome-webfont.eot?#iefix&v=4.7.0) format('embedded-opentype'), url(C:\Users\mixmix\projects\ticktack-wp1\node_modules\font-awesome\fonts/fontawesome-webfont.woff2?v=4.7.0) format('woff2'), url(C:\Users\mixmix\projects\ticktack-wp1\node_modules\font-awesome\fonts/fontawesome-webfont.woff?v=4.7.0) format('woff'), url(C:\Users\mixmix\projects\ticktack-wp1\node_modules\font-awesome\fonts/fontawesome-webfont.ttf?v=4.7.0) format('truetype'), url(C:\Users\mixmix\projects\ticktack-wp1\node_modules\font-awesome\fonts/fontawesome-webfont.svg?v=4.7.0#fontawesomeregular) format('svg');
  font-weight: normal;
  font-style: normal;
}
```
